class PyFjallMorpology:
    def __init__(self, folder: str) -> None: ...
    def build_from_path(self, path: str) -> None: ...
    def lookup(self, fragment: str) -> bytes | None: ...
    def lookup_with_cont(self, fragment: str) -> bytes: ...
